name: Panela
main: dev.matheusferreira.panelaplugin.PanelaPlugin
version: 1.1
author: ledoctah

commands:
  register:
    description: Register yourself with a password to login.
    usage: /<command> <senha>
    permission: panelaplugin.basic
    permission-message: You don't have <permission>

  login:
    description: Login with a password.
    usage: /<command> <senha>
    permission: panelaplugin.basic
    permission-message: You don't have <permission>